name: First Workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: afficher bonjour
        run: echo "Bonjour tous"
      - name: dire goodluck
        run: echo "Goooooodddd luck"
      
